### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by bpbond** [kaizadp/nmrrr#25]
* Code reformatted #10 
* All R CMD CHECK notes fixed except for `inst/extdata` size
* Bin assignment code reworked #21 
* Bins are now package data #18 
* Documentation and function exporting greatly changed #14 #17 
* Code, test code, and test data for processing code reworked and expanded #20 #24 
* Relabund code, documentation, and test code reworked #27 

I won't have much time this coming week but @kaizadp please test out the package, in particular
reading spectra and peaks files, and assigning bins. Feedback welcome.

**Comment by kaizadp** [comment]
Thanks! Working through these edits today.

**Comment by bpbond** [comment]
Thanks for merging PRs 30-34 @kaizadp . At this point, the package is pretty solid I think 🎉 

Remaining to-do items from my POV:

- [x] Transfer ownership to @kaizadp 
- [x] Resolve `KP_TODO` items - mostly these are needed documentation details #16 
- [x] Make a vignette
- [x] Let's talk about the data in `inst/extdata` - at 50+ MB, it's triggering our only NOTE (which will hold up approval on CRAN)
- [x] I would prefer to remove `dplyr` as an import; not much code actually uses it, and it's a heavy dependency #36 
- [x]  Fix the codecov badge -- not sure what's going on there
- [x] Bring over the cool hex badge and other README info from https://github.com/kaizadp/nmrrr
- [x] Add other people to DESCRIPTION? E.g. AMP
- [x] Expand package description text in DESCRIPTION
- [x] Test code for ggspectra #36 

Anything else?

**Comment by kaizadp** [comment]
> Transfer ownership to https://github.com/COMPASS-DOE ?

Possibly? This is not exclusively a COMPASS package (COMPASS/TES/RC contributions), so not sure if it's better to place it under COMPASS, or leave it as your/my repo. Let's discuss.

>  I would prefer to remove dplyr as an import; not much code actually uses it, and it's a heavy dependency. But defer to you @kaizadp

Sure! I assumed we needed to import every package that is being used in our functions, so I added it in there. But yes, let's delete if it's not needed and making the package unwieldy.

>  Let's talk about the data in inst/extdata - at 50+ MB, it's triggering our only NOTE (which will hold up approval on CRAN)

Just looked a couple of the files. `kfp_hysteresis/spectra_mnova/` files are so big because there are a lot of "crap" data (< 0 or > 10 ppm), I deleted those, and brought it down from 1.3 MB to 740 KB! I'll do this for all the files and see how much that helps the overall size.

**Comment by bpbond** [comment]
Oh, if not COMPASS, fine. I just assumed. Thanks!

**Comment by bpbond** [comment]
With e2554ea0efb364b5ccd1214e1bc2e50052a05d36 I think we're in good shape. The remaining unchecked items above are mostly on you @kaizadp : 
* Create at least one vignette (optional, but very useful for users)
* The `inst/extdata` size
* Expand package description text in DESCRIPTION file

Happy to consult about any of these! But for now, I'm moving this off my to-do list 😄

**Comment by kaizadp** [comment]
Thanks! Yep, working on these items, and I’ll tag you in Issues/PRs.

**Comment by bpbond** [comment]
Probably obvious, but: any datasets in `inst/extdata` should be used — either in `@examples` or the vignette(s).

**Comment by kaizadp** [comment]
> * [x]  Let's talk about the data in `inst/extdata` - at 50+ MB, it's triggering our only NOTE (which will hold up approval on CRAN)
> *

Finally done, PR #44

**Comment by bpbond** [comment]
@kaizadp Maybe we can touch base in the new year about this?

**Comment by kaizadp** [comment]
Yes! Sorry, it's been a crazy few weeks/months. I'll work on the vignettes soon, and we can touch base in January. Thanks!
